import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "@/components/Header";

import "./globals.css";

const pretendardSans = localFont({
  src: "../../public/font/PretendardVariable.woff2",
  variable: "--font-pretendard-sans",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendardSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
